<?php
// export_moh.php
// Generates and streams a CSV export of the MOH 240 Laboratory Register
session_start();
require_once 'includes/db_connect.php';
require_once 'includes/audit.php';

if (!isset($_SESSION['loggedin'])) {
    header("location: index.php"); exit;
}

$role = $_SESSION['role'] ?? '';
if ($role !== 'Admin' && $role !== 'Doctor') {
    die("Access denied: only Administrators and Doctors can export MOH reports.");
}

$date_from = $_GET['date_from'] ?? date('Y-m-01');
$date_to   = $_GET['date_to']   ?? date('Y-m-d');

// Validate date formats
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $date_from)) $date_from = date('Y-m-01');
if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $date_to))   $date_to   = date('Y-m-d');

$filename = "MOH_240_Yala_Hospital_" . $date_from . "_to_" . $date_to . ".csv";

// Set CSV download headers
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

$output = fopen('php://output', 'w');

// Hospital Header
fputcsv($output, ['YALA SUB-COUNTY HOSPITAL - LABORATORY DEPARTMENT']);
fputcsv($output, ['MOH 240 REGISTER EXPORT & SUMMARY REPORT']);
fputcsv($output, ['Reporting Period:', $date_from . ' to ' . $date_to]);
fputcsv($output, ['Generated By:', $_SESSION['full_name'] ?? 'Staff', 'Role:', $role]);
fputcsv($output, ['Export Date/Time:', date('Y-m-d H:i:s')]);
fputcsv($output, []); // Empty line

// Column Headers
fputcsv($output, [
    'Date / Time',
    'Request ID',
    'OPD Number',
    'Patient Name',
    'Age (Years)',
    'Gender',
    'Insurance / Scheme',
    'Test Category',
    'Test Name',
    'Result Value',
    'Normal Reference Range',
    'Units',
    'Abnormal Flag',
    'Technician Remarks',
    'Requesting Clinician',
    'Testing Technician',
    'Test Fee (KES)',
    'Request Status',
    'Payment Status'
]);

$sql = "SELECT 
            r.request_id,
            r.request_date,
            r.requested_by,
            r.status AS request_status,
            r.payment_status,
            p.opd_number,
            p.full_name AS patient_name,
            p.age,
            p.gender,
            p.insurance_provider,
            t.test_name,
            t.test_category,
            t.cost,
            t.units,
            t.normal_range,
            tr.result_value,
            tr.technician_remarks,
            u.full_name AS tech_name
        FROM test_results tr
        JOIN lab_requests r ON tr.request_id = r.request_id
        JOIN patients p ON r.patient_id = p.patient_id
        JOIN lab_tests t ON tr.test_id = t.test_id
        LEFT JOIN users u ON tr.entered_by = u.user_id
        WHERE DATE(r.request_date) BETWEEN ? AND ?
        ORDER BY r.request_date ASC, r.request_id ASC, t.test_name ASC";

$stmt = $conn->prepare($sql);
$stmt->bind_param("ss", $date_from, $date_to);
$stmt->execute();
$res = $stmt->get_result();

$total_tests = 0;
$total_cost = 0;
$pos_malaria = 0;

$abn_keywords = ['pos', 'high', 'elev', 'abnorm', 'react', '+'];

while ($row = $res->fetch_assoc()) {
    $total_tests++;
    $total_cost += floatval($row['cost']);
    
    // Check if result is abnormal
    $val = strtolower(trim($row['result_value'] ?? ''));
    $is_abn = 'No';
    foreach ($abn_keywords as $k) {
        if (str_contains($val, $k)) {
            $is_abn = 'YES (ABNORMAL)';
            break;
        }
    }
    
    if (str_contains(strtolower($row['test_name']), 'malaria') && str_contains($val, 'pos')) {
        $pos_malaria++;
    }

    fputcsv($output, [
        date('Y-m-d H:i', strtotime($row['request_date'])),
        '#' . $row['request_id'],
        $row['opd_number'],
        $row['patient_name'],
        $row['age'],
        $row['gender'],
        $row['insurance_provider'] ?: 'Cash / None',
        $row['test_category'] ?: 'General',
        $row['test_name'],
        $row['result_value'],
        $row['normal_range'] ?: '—',
        $row['units'] ?: '',
        $is_abn,
        $row['technician_remarks'] ?: '',
        'Dr. ' . $row['requested_by'],
        $row['tech_name'] ?: 'Lab Staff',
        number_format(floatval($row['cost']), 2, '.', ''),
        $row['request_status'],
        $row['payment_status']
    ]);
}
$stmt->close();

// Append Summary Section
fputcsv($output, []);
fputcsv($output, ['--- SUMMARY EPIDEMIOLOGICAL INDICATORS ---']);
fputcsv($output, ['Total Investigations Conducted:', $total_tests]);
fputcsv($output, ['Total Billed Value (KES):', number_format($total_cost, 2, '.', '')]);
fputcsv($output, ['Confirmed Positive Malaria Cases:', $pos_malaria]);

// Audit Log
audit_log($conn, 'export_moh_report', 'reports', 0, "Exported MOH 240 CSV for $date_from to $date_to");

fclose($output);
exit;
