<?php
// print_report.php

// 1. FIX: DEFINE THE FONT PATH EXPLICITLY
define('FPDF_FONTPATH','fpdf/font/');

require('fpdf/fpdf.php');
require_once 'includes/db_connect.php';

// Check if a Request ID is provided
if (!isset($_GET['id'])) {
    die("Error: No Request ID specified.");
}

$request_id = $_GET['id'];

// 1. FETCH PATIENT & REQUEST DETAILS
$sql_patient = "SELECT p.full_name, p.opd_number, p.age, p.gender, r.request_date, r.requested_by
                FROM lab_requests r
                JOIN patients p ON r.patient_id = p.patient_id
                WHERE r.request_id = $request_id";
$patient_res = $conn->query($sql_patient);
if ($patient_res->num_rows == 0) { die("Record not found."); }
$patient = $patient_res->fetch_assoc();

// 2. FETCH TEST RESULTS
$sql_tests = "SELECT t.test_name, tr.result_value, t.units, t.normal_range, tr.technician_remarks
              FROM test_results tr
              JOIN lab_tests t ON tr.test_id = t.test_id
              WHERE tr.request_id = $request_id";
$tests_res = $conn->query($sql_tests);

// --- START PDF GENERATION ---

class PDF extends FPDF {
    // Page Header
    function Header() {
        // --- FIX: ADD LOGO IF IT EXISTS ---
        // Ensure you have a file named 'logo.png' in your yala_lims folder
        if(file_exists('logo.png')) {
            $this->Image('logo.png', 10, 10, 25); 
        }

        // --- FIX: BETTER HEADER STYLING ---
        $this->SetFont('Arial', 'B', 18);
        $this->SetTextColor(33, 37, 41); // Dark Gray
        // Move to the right to avoid overlapping the logo
        $this->Cell(30); 
        $this->Cell(0, 10, 'YALA SUB-COUNTY HOSPITAL', 0, 1, 'C');
        
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(30);
        $this->Cell(0, 7, 'DEPARTMENT OF LABORATORY SERVICES', 0, 1, 'C');
        
        $this->SetFont('Arial', '', 10);
        $this->SetTextColor(100, 100, 100); // Light Gray
        $this->Cell(30);
        $this->Cell(0, 5, 'P.O. Box 45 - 40610, Yala | Tel: 0700-000-000', 0, 1, 'C');
        
        $this->Ln(15);
        $this->SetDrawColor(0, 0, 0);
        $this->Line(10, 42, 200, 42); // Horizontal line
        $this->Ln(5);
    }

    // Page Footer
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial','I',8);
        $this->SetTextColor(128); // Grey
        $this->Cell(0,10,'Page '.$this->PageNo().' | Generated by Yala LIMS System',0,0,'C');
    }
}

$pdf = new PDF();
$pdf->AddPage();

// SECTION A: PATIENT DETAILS
$pdf->SetTextColor(0, 0, 0); // Reset to black
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0, 10, 'PATIENT LABORATORY REPORT', 0, 1, 'L');

$pdf->SetFont('Arial','',10);
// Row 1
$pdf->Cell(40, 7, 'Patient Name:', 0, 0);
$pdf->Cell(60, 7, $patient['full_name'], 0, 0);
$pdf->Cell(40, 7, 'Date:', 0, 0);
$pdf->Cell(50, 7, date('d-M-Y H:i', strtotime($patient['request_date'])), 0, 1);

// Row 2
$pdf->Cell(40, 7, 'OPD Number:', 0, 0);
$pdf->Cell(60, 7, $patient['opd_number'], 0, 0);
$pdf->Cell(40, 7, 'Age/Gender:', 0, 0);
$pdf->Cell(50, 7, $patient['age'] . ' Yrs / ' . $patient['gender'], 0, 1);

// Row 3
$pdf->Cell(40, 7, 'Requested By:', 0, 0);
$pdf->Cell(60, 7, 'Dr. ' . $patient['requested_by'], 0, 1);

$pdf->Ln(5); // Spacer

// SECTION B: TEST RESULTS TABLE
$pdf->SetFont('Arial','B',10);
$pdf->SetFillColor(200, 220, 255); // Light Blue Header

// Table Header
$pdf->Cell(60, 8, 'Test Name', 1, 0, 'L', true);
$pdf->Cell(40, 8, 'Result', 1, 0, 'C', true);
$pdf->Cell(40, 8, 'Units / Ref', 1, 0, 'C', true);
$pdf->Cell(50, 8, 'Remarks', 1, 1, 'L', true);

// Table Rows
$pdf->SetFont('Arial','',10);

while($row = $tests_res->fetch_assoc()) {
    $pdf->Cell(60, 8, $row['test_name'], 1, 0);
    
    // --- FIX: SMART COLOR LOGIC START ---
    // Check for "Positive" or "High" in the result text
    $is_abnormal = false;
    // 'stripos' searches for text regardless of capital/small letters
    if (stripos($row['result_value'], 'Pos') !== false || stripos($row['result_value'], 'High') !== false) {
        $is_abnormal = true;
    }

    if ($is_abnormal) {
        $pdf->SetTextColor(255, 0, 0); // RED
        $pdf->SetFont('Arial', 'B', 10); // BOLD
    } else {
        $pdf->SetTextColor(0, 0, 0); // BLACK
        $pdf->SetFont('Arial', '', 10);
    }
    // --- SMART LOGIC END ---

    $pdf->Cell(40, 8, $row['result_value'], 1, 0, 'C');
    
    // Reset colors for the next columns
    $pdf->SetTextColor(0, 0, 0); 
    $pdf->SetFont('Arial', '', 10);
    
    $pdf->Cell(40, 8, $row['units'] . ' ' . $row['normal_range'], 1, 0, 'C');
    $pdf->Cell(50, 8, $row['technician_remarks'], 1, 1, 'L');
}

$pdf->Ln(15);

// SECTION C: SIGNATURES
$pdf->SetFont('Arial','',10);
$pdf->Cell(100, 5, '................................................', 0, 1);
$pdf->Cell(100, 5, 'Lab Technologist Signature', 0, 1);

$pdf->Output(); // Send PDF to browser
?>